package io.github.ykwyuta.j2r.backend;

import io.github.ykwyuta.j2r.common.DiagnosticCode;
import io.github.ykwyuta.j2r.common.Diagnostics;
import io.github.ykwyuta.j2r.common.SourcePos;
import io.github.ykwyuta.j2r.rir.RExpr;
import io.github.ykwyuta.j2r.rir.RFile;
import io.github.ykwyuta.j2r.rir.RItem;
import io.github.ykwyuta.j2r.rir.RStmt;
import io.github.ykwyuta.j2r.rir.RustPrinter;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * 変換結果を Cargo プロジェクトとして書き出す（構成は docs/04-directory-structure.md §6）。
 */
public final class CargoProjectWriter {

    /** 生成コードで抑止する lint。Java では合法な未使用変数・未使用コードなどを警告にしない。 */
    static final List<String> CRATE_ALLOWS = List.of(
            "allow(unused_variables, unused_assignments, unused_mut, dead_code, unreachable_code)");

    /**
     * @param runtimePath jrt を参照するパス（null なら出力先の jrt/ にソースを同梱する）
     */
    public record Config(Path outputDir, String crateName, Path runtimePath) {}

    /** 1 つの生成ファイル（src/ からの相対パスと内容）。 */
    public record GeneratedFile(String path, String content) {}

    private final Config config;
    private final Diagnostics diags;

    public CargoProjectWriter(Config config, Diagnostics diags) {
        this.config = config;
        this.diags = diags;
    }

    /**
     * @param files      クラスごとのファイル
     * @param modules    各ファイルのモジュールパス（files と同順）
     * @param mainModule main 関数を持つモジュール（null ならライブラリのみ）
     * @return 書き出した src/ 配下のファイル
     */
    public List<GeneratedFile> write(List<RFile> files, List<List<String>> modules, List<String> mainModule) {
        List<GeneratedFile> out = new ArrayList<>();
        for (RFile f : files) {
            out.add(new GeneratedFile(f.path(), RustPrinter.print(f)));
        }
        out.addAll(moduleTree(modules));
        if (mainModule != null) {
            out.add(new GeneratedFile("bin/main.rs", mainRs(mainModule)));
        }
        try {
            Path root = config.outputDir();
            Path src = root.resolve("src");
            deleteRecursively(src);
            Files.createDirectories(src);
            for (GeneratedFile g : out) {
                Path p = src.resolve(g.path());
                Files.createDirectories(p.getParent());
                Files.writeString(p, g.content(), StandardCharsets.UTF_8);
            }
            Files.writeString(root.resolve("Cargo.toml"), cargoToml(mainModule != null), StandardCharsets.UTF_8);
            if (config.runtimePath() == null) {
                vendorRuntime(root.resolve("jrt"));
            }
            Files.writeString(root.resolve(".gitignore"), "/target\n", StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return out;
    }

    /** lib.rs と、パッケージごとの mod.rs を作る。 */
    private List<GeneratedFile> moduleTree(List<List<String>> modules) {
        // ディレクトリ（パッケージ）→ 直下のモジュール名
        Map<String, java.util.SortedSet<String>> children = new TreeMap<>();
        java.util.Set<String> leaves = new java.util.HashSet<>();
        children.put("", new java.util.TreeSet<>());
        for (List<String> m : modules) {
            leaves.add(String.join("/", m));
            for (int i = 0; i < m.size(); i++) {
                String dir = String.join("/", m.subList(0, i));
                children.computeIfAbsent(dir, k -> new java.util.TreeSet<>()).add(m.get(i));
            }
        }
        List<GeneratedFile> out = new ArrayList<>();
        for (var e : children.entrySet()) {
            String dir = e.getKey();
            if (!dir.isEmpty() && leaves.contains(dir)) {
                diags.report(DiagnosticCode.NAME_COLLISION, SourcePos.UNKNOWN,
                        "module '" + dir.replace('/', ':') + "' is both a class and a package");
            }
            List<RItem> items = new ArrayList<>();
            for (String child : e.getValue()) {
                items.add(new RItem.ModDecl(true, child));
            }
            if (dir.isEmpty()) {
                List<String> docs = List.of("Generated by Java2RustTranslator. Do not edit by hand; re-run the translator instead.");
                out.add(new GeneratedFile("lib.rs", RustPrinter.print(new RFile("lib.rs", docs, CRATE_ALLOWS, items))));
            } else {
                out.add(new GeneratedFile(dir + "/mod.rs", RustPrinter.print(new RFile(dir + "/mod.rs", List.of(), List.of(), items))));
            }
        }
        return out;
    }

    private String mainRs(List<String> mainModule) {
        String path = config.crateName() + "::" + String.join("::", mainModule) + "::main";
        RExpr call = new RExpr.Call(new RExpr.Path("jrt::run_main"),
                List.of(new RExpr.Closure(List.of("args"), new RExpr.Call(new RExpr.Path(path), List.of(new RExpr.Path("args"))))));
        RItem.Fn main = new RItem.Fn(List.of(), false, "main", List.of(), null,
                RExpr.Block.of(List.of(new RStmt.ExprStmt(call, true))));
        return RustPrinter.print(new RFile("bin/main.rs", List.of("Entry point generated by Java2RustTranslator."), List.of(), List.of(main)));
    }

    private String cargoToml(boolean hasMain) {
        String jrt = config.runtimePath() == null ? "jrt" : config.runtimePath().toAbsolutePath().normalize().toString().replace('\\', '/');
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Java2RustTranslator.\n");
        sb.append("[package]\n");
        sb.append("name = \"").append(config.crateName()).append("\"\n");
        sb.append("version = \"0.1.0\"\n");
        sb.append("edition = \"2021\"\n");
        sb.append("publish = false\n");
        // クラス名が Main の場合 src/main.rs がモジュールになりうるため、バイナリの自動検出は切る。
        sb.append("autobins = false\n\n");
        sb.append("[lib]\npath = \"src/lib.rs\"\n\n");
        if (hasMain) {
            sb.append("[[bin]]\nname = \"").append(config.crateName()).append("\"\npath = \"src/bin/main.rs\"\n\n");
        }
        sb.append("[dependencies]\n");
        sb.append("jrt = { path = \"").append(jrt).append("\" }\n\n");
        sb.append("# 生成物は独立したワークスペースとして扱う（親ディレクトリのワークスペースに取り込まれないように）。\n");
        sb.append("[workspace]\n");
        return sb.toString();
    }

    /** jar に同梱された jrt のソースを dest にコピーする。 */
    static void vendorRuntime(Path dest) throws IOException {
        ClassLoader cl = CargoProjectWriter.class.getClassLoader();
        String base = "j2r/runtime/jrt/";
        List<String> files;
        try (InputStream in = cl.getResourceAsStream(base + "index.txt")) {
            if (in == null) {
                throw new IllegalStateException("bundled jrt runtime not found on classpath");
            }
            files = new String(in.readAllBytes(), StandardCharsets.UTF_8).lines().filter(l -> !l.isBlank()).toList();
        }
        deleteRecursively(dest);
        for (String f : files) {
            try (InputStream in = cl.getResourceAsStream(base + f)) {
                if (in == null) {
                    throw new IllegalStateException("bundled jrt file missing: " + f);
                }
                Path p = dest.resolve(f);
                Files.createDirectories(p.getParent());
                Files.write(p, in.readAllBytes());
            }
        }
    }

    private static void deleteRecursively(Path p) throws IOException {
        if (!Files.exists(p)) {
            return;
        }
        try (var walk = Files.walk(p)) {
            for (Path x : walk.sorted(java.util.Comparator.reverseOrder()).toList()) {
                Files.delete(x);
            }
        }
    }
}
